name: Code Smell Check

on:
  push:
    branches: [main]

jobs:
  check-smells:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install eslint
    - name: Run code smell check
      run: npx eslint .
